version: '3.3'

services:
  mongo:
    image: mongo:4.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
      - MONGO_INITDB_DATABASE=mydb
    networks:
      - server-net

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: node-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://admin:adminpassword@mongo:27017/mydb?authSource=admin
      - JWT_SECRET=lpdgXKidkVOrbOEYNI8QCXVN9ji6k3HF
    depends_on:
      - mongo
    networks:
      - server-net

volumes:
  mongo_data:

networks:
  server-net:
